title: FeliX
description: Documentation for the FeliX Model
# remote_theme: just-the-docs
remote_theme: pmarsceill/just-the-docs
url: ""

logo: /images/felix_doc_logo.png

search_enabled: false
google_analytics: G-4NR9BJ5YPK
aux_links:
  "FeliX model on GitHub":
    - "https://github.com/iiasa/Felix-Model"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true

math: katex

footer_content: "Copyright (c); 2024- IIASA/RU . This work is licensed under a <a href=\"http://creativecommons.org/licenses/by/4.0\">Creative Commons Attribution 4.0 International License</a>."

